name: Release Stable Kernel

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create archives
        id: packaging
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          cd pub/stable
          for kernel_dir in ./*; do [ -d "${kernel_dir}" ] && tar -czvf "${kernel_dir}.tar.gz" "${kernel_dir}"; done
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.packaging.outputs.status }} == 'success' && !cancelled()
        with:
          tag: kernel_stable
          artifacts: pub/*/*.tar.gz
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            The kernel can be used to compile Armbian and OpenWrt.
